#!/usr/bin/env python3
"""
Generate Pkl modules from an APISIX schema snapshot (see tools/fetch-schema.sh).

Usage:
  python3 tools/generate.py schema/apisix-<version>.json

Writes:
  src/Apisix.pkl            core resources (Route, Service, Upstream, ...)
  src/Common.pkl            object types shared by several modules (plugin `_meta`, ...)
  src/Plugins.pkl           Plugins / ConsumerPlugins / StreamPlugins / PluginMetadata
  src/plugins/<name>.pkl    one module per HTTP plugin
  src/stream/<name>.pkl     one module per stream plugin
  build/typeinfo.json       type map used by tools/docs_examples.py
  COVERAGE.md               what is and is not checked by Pkl

Mapping rules (JSON Schema → Pkl):
  object + properties        → open class; optional properties are `T?` and default to null,
                               so APISIX applies its own defaults (documented in doc comments)
  object + pattern/additionalProperties → Mapping<String, T>
  array                      → Listing<T>
  enum / const               → literal union
  oneOf/anyOf of types       → union type
  required/not/oneOf/anyOf/allOf/if/dependencies/min|maxProperties on an object
                             → compiled to a constraint on `typealias Valid<Class>`
  everything Pkl cannot express is listed in COVERAGE.md; APISIX still checks it at load time.
"""

from __future__ import annotations

import json
import os
import re
import sys
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")
HEADER = "// Code generated by tools/generate.py from {schema}. DO NOT EDIT.\n"

PKL_KEYWORDS = {
    "abstract", "amends", "as", "case", "class", "const", "default", "delete", "else", "extends",
    "external", "false", "fixed", "for", "function", "hidden", "if", "import", "in", "is",
    "let", "local", "module", "new", "nothing", "null", "open", "out", "outer", "override",
    "protected", "read", "record", "super", "switch", "this", "throw", "throws", "trace",
    "true", "typealias", "unknown", "vararg", "when",
}
DOC_KEYS = {"description", "$comment", "title", "default", "examples", "encrypt_fields"}
COMBINATORS = ("oneOf", "anyOf", "allOf", "not", "if", "then", "else", "dependencies")

# Core resources rendered into Apisix.pkl: schema key → class name.
MAIN = {
    "upstream": "Upstream",
    "route": "Route",
    "service": "Service",
    "consumer": "Consumer",
    "credential": "Credential",
    "consumer_group": "ConsumerGroup",
    "ssl": "Ssl",
    "global_rule": "GlobalRule",
    "plugin_config": "PluginConfig",
    "proto": "Proto",
    "stream_route": "StreamRoute",
}
# Helper schemas APISIX uses internally; not resources of apisix.yaml.
MAIN_SKIPPED = {
    "graphql_cost_decoration": "internal helper of the graphql-limit-count plugin",
    "upstream_hash_header_schema": "internal check of upstream.key when hash_on = header",
    "upstream_hash_vars_schema": "internal check of upstream.key when hash_on = vars",
}
# `plugins` fields typed as `{"type": "object"}` in the schema: path → (module, class).
PLUGIN_FIELDS = {
    "route.plugins": "Plugins",
    "service.plugins": "Plugins",
    "plugin_config.plugins": "Plugins",
    "global_rule.plugins": "Plugins",
    "consumer_group.plugins": "Plugins",
    "consumer.plugins": "ConsumerPlugins",
    "credential.plugins": "ConsumerPlugins",
    "stream_route.plugins": "StreamPlugins",
}
# Nicer names for shared object types (property key → class name).
SHARED_NAMES = {"_meta": "PluginMeta"}


# ---------------------------------------------------------------- helpers


def pascal(name: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", name)
    out = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if not out or out[0].isdigit():
        out = "T" + out
    return out


def ident(name: str) -> str:
    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", name) and name not in PKL_KEYWORDS:
        return name
    return "`" + name.replace("`", "") + "`"


def canon(schema) -> str:
    return json.dumps(schema, sort_keys=True)


def pkl_string(s: str) -> str:
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20:
            out.append("\\u{%x}" % ord(ch))
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


POSIX_CLASSES = {
    "alpha": r"\p{Alpha}", "digit": r"\p{Digit}", "alnum": r"\p{Alnum}", "upper": r"\p{Upper}",
    "lower": r"\p{Lower}", "space": r"\s", "punct": r"\p{Punct}", "xdigit": r"\p{XDigit}",
    "print": r"\p{Print}", "graph": r"\p{Graph}", "cntrl": r"\p{Cntrl}", "blank": r"\p{Blank}",
}


def java_regex(pattern: str) -> str:
    r"""Translate a PCRE pattern (what APISIX uses) to Java syntax (what Pkl uses).

    Inside a character class PCRE treats `[` and `&&` literally; Java starts a nested class
    or an intersection. POSIX classes such as `[:alpha:]` become `\p{Alpha}`.
    """
    out, i, in_class, n = [], 0, False, len(pattern)
    while i < n:
        ch = pattern[i]
        if ch == "\\" and i + 1 < n:
            out.append(pattern[i:i + 2])
            i += 2
            continue
        if in_class:
            m = re.match(r"\[:(\w+):\]", pattern[i:])
            if m and m.group(1) in POSIX_CLASSES:
                out.append(POSIX_CLASSES[m.group(1)])
                i += m.end()
                continue
            if ch == "[":
                out.append("\\[")
            elif ch == "&" and pattern[i:i + 2] == "&&":
                out.append("\\&\\&")
                i += 2
                continue
            elif ch == "]" and out and out[-1] not in ("[", "[^"):
                in_class = False
                out.append(ch)
            else:
                out.append(ch)
            i += 1
            continue
        if ch == "[":
            in_class = True
            if pattern[i:i + 2] == "[^":
                out.append("[^")
                i += 2
            else:
                out.append("[")
                i += 1
            if i < n and pattern[i] == "]":  # leading ] is literal
                out.append("\\]")
                i += 1
            continue
        out.append(ch)
        i += 1
    return "".join(out)


def pkl_regex(pattern: str) -> str:
    pattern = java_regex(pattern)
    n = 1
    while ('"' + "#" * n) in pattern or ("\\" + "#" * n) in pattern:
        n += 1
    h = "#" * n
    return f'Regex({h}"{pattern}"{h})'


def pkl_literal(v) -> str | None:
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v) if "e" not in repr(v) else f"{v:.20f}".rstrip("0")
    if isinstance(v, str):
        return pkl_string(v)
    return None  # objects / arrays have no literal type form


def literal_type(values: list) -> str | None:
    strs = [v for v in values if isinstance(v, str)]
    ints = [v for v in values if isinstance(v, int) and not isinstance(v, bool)]
    nums = [v for v in values if isinstance(v, float)]
    bools = [v for v in values if isinstance(v, bool)]
    if len(strs) + len(ints) + len(nums) + len(bools) != len(values):
        return None
    parts = [pkl_string(s) for s in dict.fromkeys(strs)]
    if ints:
        parts.append("Int(" + " || ".join(f"this == {i}" for i in dict.fromkeys(ints)) + ")")
    if nums:
        parts.append("Number(" + " || ".join(f"this == {pkl_literal(n)}" for n in dict.fromkeys(nums)) + ")")
    if bools:
        parts.append("Boolean(" + " || ".join(f"this == {pkl_literal(b)}" for b in dict.fromkeys(bools)) + ")")
    return "|".join(parts)


def doc_lines(schema: dict, indent: str) -> list[str]:
    lines = []
    desc = schema.get("description") or schema.get("title")
    if desc:
        lines += [l.rstrip() for l in str(desc).strip().splitlines()]
    if "default" in schema:
        d = json.dumps(schema["default"])
        lines.append(f"Default: `{d}`" if len(d) <= 120 else "Default: (see APISIX docs)")
    if "format" in schema:
        lines.append(f"Format: {schema['format']} (not checked by Pkl)")
    return [f"{indent}/// {l}" if l else f"{indent}///" for l in lines]


def nullable(t: str) -> str:
    return f"({t})?" if "|" in t else f"{t}?"


# ---------------------------------------------------------------- model


class Module:
    def __init__(self, rel: str, name: str, doc: list[str]):
        self.rel = rel          # path relative to src/
        self.name = name        # Pkl module name
        self.doc = doc
        self.imports: dict[str, str] = {}  # alias → relative import path
        self.blocks: list[str] = []
        self.names: set[str] = set()
        self.local: dict[str, tuple[str, dict]] = {}  # canon → (type expr, info)

    def unique(self, name: str) -> str:
        base, n = name, 2
        while name in self.names:
            name, n = f"{base}{n}", n + 1
        self.names.add(name)
        return name

    def alias(self) -> str:
        return re.sub(r"[^A-Za-z0-9_]", "_", os.path.splitext(os.path.basename(self.rel))[0])

    def ref(self, target: "Module", name: str) -> str:
        if target is self:
            return name
        alias = target.alias()
        if target.rel.startswith("stream/") and not self.rel.startswith("stream/"):
            alias = "stream_" + alias
        path = os.path.relpath(os.path.join(SRC, target.rel), os.path.dirname(os.path.join(SRC, self.rel)))
        self.imports[alias] = path
        return f"{alias}.{name}"

    def render(self, schema_name: str) -> str:
        out = [HEADER.format(schema=schema_name)]
        out += [f"/// {l}" if l else "///" for l in self.doc]
        out.append(f"module {self.name}\n")
        for alias, path in sorted(self.imports.items()):
            out.append(f'import "{path}" as {alias}')
        if self.imports:
            out.append("")
        out.append("\n\n".join(self.blocks))
        return "\n".join(out).rstrip() + "\n"


class Stats:
    def __init__(self):
        self.classes = 0
        self.properties = 0
        self.rules_compiled = 0
        self.rules_skipped: list[tuple[str, str]] = []   # (path, json)
        self.open_objects: list[str] = []
        self.tuples: list[str] = []
        self.misc: list[tuple[str, str]] = []            # (path, keyword)
        self.patterns: list[str] = []
        self.named_patterns: list[str] = []


# ---------------------------------------------------------------- generator


class Generator:
    def __init__(self, schema: dict, schema_name: str):
        self.schema = schema
        self.schema_name = schema_name
        self.stats = Stats()
        self.modules: dict[str, Module] = {}
        self.shared: dict[str, tuple[Module, str, str, dict]] = {}  # canon → (module, name, type, info)
        self.shared_candidates: set[str] = set()
        self.typeinfo: dict[str, dict] = {}
        self._finfo: dict[str, list] = defaultdict(list)
        self.scalar_counts: Counter = Counter()
        self.scalar_aliases: dict[str, str] = {}

    # ---------------------------------------------------------- modules

    def module(self, rel: str, name: str, doc: list[str]) -> Module:
        if rel not in self.modules:
            self.modules[rel] = Module(rel, name, doc)
        return self.modules[rel]

    # ---------------------------------------------------------- types

    def type_of(self, s, hint: str, mod: Module, path: str) -> tuple[str, dict]:
        """Return (Pkl type expression, typeinfo descriptor) for schema `s`."""
        t, info = self.type_of_inner(s, hint, mod, path)
        if len(t) > 60 and isinstance(s, dict) and not self.has_class(info) \
                and self.scalar_counts.get(canon(s), 0) > 1:
            key = canon(s)
            if key not in self.scalar_aliases:
                common = self.modules["Common.pkl"]
                t, info = self.type_of_inner(s, hint, common, path)
                prop = re.sub(r"[\[\]{}|0-9]+$", "", path.rsplit(".", 1)[-1]) or "Value"
                name = common.unique(pascal(prop))
                common.blocks.append("\n".join(doc_lines({"description": s.get("description")}, "")
                                               + [f"typealias {name} = {t}"]))
                self.scalar_aliases[key] = name
            return mod.ref(self.modules["Common.pkl"], self.scalar_aliases[key]), info
        return t, info

    @classmethod
    def has_class(cls, info: dict) -> bool:
        if info.get("k") == "class":
            return True
        of = info.get("of")
        if isinstance(of, list):
            return any(cls.has_class(i) for i in of)
        return isinstance(of, dict) and cls.has_class(of)

    def type_of_inner(self, s, hint: str, mod: Module, path: str) -> tuple[str, dict]:
        if s is True or s == {} or s is None:
            return "Any", {"k": "any"}
        if path in PLUGIN_FIELDS:
            plugins = self.modules["Plugins.pkl"]
            return mod.ref(plugins, PLUGIN_FIELDS[path]), {"k": "class", "ref": f"Plugins.pkl#{PLUGIN_FIELDS[path]}"}

        if "enum" in s:
            lt = literal_type(s["enum"])
            if lt:
                return lt, {"k": "scalar"}
        if "const" in s:
            lt = literal_type([s["const"]])
            if lt:
                return lt, {"k": "scalar"}

        types = s.get("type")
        if isinstance(types, list):
            parts = [self.type_of({**s, "type": t}, hint, mod, path) for t in types]
            return self.union(parts)

        kind = types or self.infer_kind(s)
        if kind == "object":
            return self.object_type(s, hint, mod, path)

        # Structural oneOf/anyOf on a non-object node → union of branches.
        for comb in ("oneOf", "anyOf"):
            if comb in s and all(isinstance(b, dict) and self.is_structural(b) for b in s[comb]):
                base = {k: v for k, v in s.items() if k not in ("oneOf", "anyOf")}
                parts = [
                    self.type_of({**base, **b}, f"{hint}Option{i + 1}", mod, f"{path}|{i}")
                    for i, b in enumerate(s[comb])
                ]
                return self.union(parts)

        for k in ("oneOf", "anyOf", "allOf", "not", "if", "contains"):
            if k in s:
                self.stats.misc.append((path, k))

        if kind == "string":
            c = []
            if "minLength" in s:
                c.append(f"length >= {s['minLength']}")
            if "maxLength" in s:
                c.append(f"length <= {s['maxLength']}")
            if "pattern" in s:
                c.append(f"contains({pkl_regex(s['pattern'])})")
                self.stats.patterns.append(s["pattern"])
            return self.constrained("String", c), {"k": "scalar"}
        if kind in ("integer", "number"):
            base = "Int" if kind == "integer" else "Number"
            return self.constrained(base, self.number_constraints(s)), {"k": "scalar"}
        if kind == "boolean":
            return "Boolean", {"k": "scalar"}
        if kind == "null":
            return "Null", {"k": "scalar"}
        if kind == "array":
            items = s.get("items")
            if isinstance(items, list):
                self.stats.tuples.append(path)
                elem, einfo = "Any", {"k": "any"}
            elif isinstance(items, dict) and items:
                elem, einfo = self.type_of(items, self.item_name(hint), mod, f"{path}[]")
            else:
                elem, einfo = "Any", {"k": "any"}
            c = []
            if "minItems" in s:
                c.append("!isEmpty" if s["minItems"] == 1 else f"length >= {s['minItems']}")
            if "maxItems" in s:
                c.append(f"length <= {s['maxItems']}")
            if s.get("uniqueItems"):
                c.append("isDistinct")
            if "contains" in s:
                self.stats.misc.append((path, "contains"))
            return self.constrained(f"Listing<{elem}>", c), {"k": "listing", "of": einfo}
        return "Any", {"k": "any"}

    @staticmethod
    def infer_kind(s: dict) -> str | None:
        if any(k in s for k in ("properties", "patternProperties", "additionalProperties", "required")):
            return "object"
        if "items" in s:
            return "array"
        return None

    @classmethod
    def is_structural(cls, b) -> bool:
        if not isinstance(b, dict):
            return False
        if any(k in b for k in ("type", "properties", "items", "enum", "const", "patternProperties")):
            return True
        return any(k in b and all(cls.is_structural(x) for x in b[k]) for k in ("oneOf", "anyOf"))

    def union(self, parts: list[tuple[str, dict]]) -> tuple[str, dict]:
        types, infos = [], []
        for t, i in parts:
            if t == "Any":
                return "Any", {"k": "any"}
            if t not in types:
                types.append(t)
                infos.append(i)
        for base in ("String", "Int", "Number"):
            if base in types:
                keep = [i for i, t in enumerate(types) if not (t.startswith(base + "(") or t == base) or t == base]
                types, infos = [types[i] for i in keep], [infos[i] for i in keep]
        if "Number" in types:
            keep = [i for i, t in enumerate(types) if not t.startswith("Int")]
            types, infos = [types[i] for i in keep], [infos[i] for i in keep]
        if len(types) == 1:
            return types[0], infos[0]
        wrapped = [f"({t})" if "|" in t else t for t in types]
        # Default member, so `prop { ... }` amends the object form instead of building a Dynamic.
        for kind in ("class", "listing", "mapping"):
            idx = next((i for i, info in enumerate(infos) if info.get("k") == kind), None)
            if idx is not None:
                wrapped[idx] = "*" + wrapped[idx]
                break
        return "|".join(wrapped), {"k": "union", "of": infos}

    @staticmethod
    def constrained(base: str, c: list[str]) -> str:
        return f"{base}({', '.join(c)})" if c else base

    @staticmethod
    def number_constraints(s: dict) -> list[str]:
        c = []
        if "minimum" in s:
            op = ">" if s.get("exclusiveMinimum") is True else ">="
            c.append(f"this {op} {pkl_literal(s['minimum'])}")
        if "maximum" in s:
            op = "<" if s.get("exclusiveMaximum") is True else "<="
            c.append(f"this {op} {pkl_literal(s['maximum'])}")
        for k, op in (("exclusiveMinimum", ">"), ("exclusiveMaximum", "<")):
            if k in s and not isinstance(s[k], bool):
                c.append(f"this {op} {pkl_literal(s[k])}")
        if "multipleOf" in s:
            c.append(f"this % {pkl_literal(s['multipleOf'])} == 0")
        return c

    @staticmethod
    def item_name(hint: str) -> str:
        if hint.endswith("ies"):
            return hint[:-3] + "y"
        if hint.endswith("s") and not hint.endswith("ss") and len(hint) > 3:
            return hint[:-1]
        return hint + "Item"

    # ---------------------------------------------------------- objects

    def object_type(self, s: dict, hint: str, mod: Module, path: str) -> tuple[str, dict]:
        named = self.literal_pattern_properties(s)
        if named:
            # patternProperties that only name keys (`aws`, `^header$`): a class reads and types better.
            s = {k: v for k, v in s.items() if k != "patternProperties"}
            s["properties"] = named
            self.stats.named_patterns.append(path)
        props = self.merged_properties(s)
        if not props and "properties" not in s:
            return self.mapping_type(s, hint, mod, path)

        key = canon(s)
        if key in mod.local:
            return mod.local[key]
        if key in self.shared:
            smod, name, t, info = self.shared[key]
            return (mod.ref(smod, t), info)
        target = mod
        if key in self.shared_candidates:
            target = self.modules["Common.pkl"]
            prop_key = path.rsplit(".", 1)[-1]
            hint = SHARED_NAMES.get(prop_key, hint)
        name = target.unique(hint)
        info = {"k": "class", "ref": f"{target.rel}#{name}"}
        # Register before generating children (guards against recursion).
        placeholder = (name, info)
        if target is mod:
            mod.local[key] = placeholder
        else:
            self.shared[key] = (target, name, name, info)

        t = self.emit_class(s, props, name, target, path)
        if target is mod:
            mod.local[key] = (t, info)
            return t, info
        self.shared[key] = (target, name, t, info)
        return mod.ref(target, t), info

    @staticmethod
    def literal_pattern_properties(s: dict) -> dict | None:
        pp = s.get("patternProperties")
        if not pp or s.get("properties"):
            return None
        names = {}
        for pat, ps in pp.items():
            m = re.fullmatch(r"\^?([A-Za-z][A-Za-z0-9_-]*)\$?", pat)
            if not m:
                return None
            names[m.group(1)] = ps
        return names

    def merged_properties(self, s: dict) -> dict:
        props = dict(s.get("properties") or {})
        declared = set(props)  # branches only narrow these; the declaration wins

        def add(branch):
            if not isinstance(branch, dict):
                return
            for p, ps in (branch.get("properties") or {}).items():
                if p not in props:
                    props[p] = ps
                elif p not in declared and props[p] != ps and isinstance(props[p], dict) and isinstance(ps, dict):
                    if self.is_structural(ps) and self.is_structural(props[p]):
                        existing = props[p]
                        if ps.get("type") != existing.get("type") or "enum" in ps or "enum" in existing:
                            props[p] = {"anyOf": [existing, ps]}
            for comb in ("oneOf", "anyOf", "allOf"):
                for b in branch.get(comb, []):
                    add(b)
            for k in ("then", "else"):
                add(branch.get(k))
            for dep in (branch.get("dependencies") or {}).values():
                add(dep)

        for comb in ("oneOf", "anyOf", "allOf"):
            for b in s.get(comb, []):
                add(b)
        for k in ("then", "else"):
            add(s.get(k))
        for dep in (s.get("dependencies") or {}).values():
            add(dep)
        return props

    def mapping_type(self, s: dict, hint: str, mod: Module, path: str) -> tuple[str, dict]:
        values, keys = [], []
        for pat, ps in (s.get("patternProperties") or {}).items():
            values.append(self.type_of(ps, self.item_name(hint), mod, f"{path}{{{pat}}}"))
            if pat not in (".*", "^.*$"):
                keys.append(pat)
                self.stats.patterns.append(pat)
        ap = s.get("additionalProperties", True)
        if isinstance(ap, dict):
            values.append(self.type_of(ap, self.item_name(hint), mod, f"{path}{{}}"))
            keys = []
        elif ap is True and s.get("patternProperties") and not any(
                p in (".*", "^.*$") for p in s["patternProperties"]):
            values.append(("Any", {"k": "any"}))
            keys = []
        vt, vinfo = self.union(values) if values else ("Any", {"k": "any"})
        kt = "String"
        if keys:
            kt = "String(" + " || ".join(f"contains({pkl_regex(k)})" for k in keys) + ")"
        c = []
        if "minProperties" in s:
            c.append("!isEmpty" if s["minProperties"] == 1 else f"length >= {s['minProperties']}")
        if "maxProperties" in s:
            c.append(f"length <= {s['maxProperties']}")
        for k in COMBINATORS:
            if k in s:
                self.stats.misc.append((path, k))
        return self.constrained(f"Mapping<{kt}, {vt}>", c), {"k": "mapping", "of": vinfo}

    def emit_class(self, s: dict, props: dict, name: str, mod: Module, path: str) -> str:
        self.stats.classes += 1
        required = set(s.get("required") or [])
        lines = doc_lines(s, "")
        is_open = self.is_open(s)
        if is_open:
            self.stats.open_objects.append(path)
            base = mod.ref(self.modules["Base.pkl"], "OpenObject")
            lines.append(f"open class {name} extends {base} {{")
        else:
            lines.append(f"open class {name} {{")
        cinfo = {}
        for p, ps in props.items():
            self.stats.properties += 1
            ps = ps if isinstance(ps, dict) else {}
            t, info = self.type_of(ps, name + pascal(p), mod, f"{path}.{p}")
            cinfo[p] = info
            req = p in required and "default" not in ps
            lines += doc_lines(ps, "  ")
            lines.append(f"  {ident(p)}: {t if req else nullable(t)}")
        lines.append("}")
        if is_open:
            cinfo["$open"] = True
        self.typeinfo[f"{mod.rel}#{name}"] = cinfo

        rules = self.class_rules(s, props, path)
        result = name
        if rules:
            valid = mod.unique("Valid" + name)
            body = ",\n  ".join(rules)
            lines.append("")
            lines.append(f"/// [{name}] with the cross-field rules of the APISIX schema.")
            lines.append(f"typealias {valid} = {name}(\n  {body}\n)")
            result = valid
            self.typeinfo[f"{mod.rel}#{valid}"] = cinfo
        mod.blocks.append("\n".join(lines))
        return result

    @staticmethod
    def is_open(s: dict) -> bool:
        ap = s.get("additionalProperties", True)
        return ap is not False or "patternProperties" in s

    # ---------------------------------------------------------- rules

    def class_rules(self, s: dict, props: dict, path: str) -> list[str]:
        self.rule_open = self.is_open(s)
        rules = []
        for k in ("allOf", "anyOf", "oneOf", "not", "dependencies", "minProperties", "maxProperties"):
            if k in s:
                self.rule(rules, {k: s[k]}, props, path, k)
        if "if" in s:
            part = {k: s[k] for k in ("if", "then", "else") if k in s}
            self.rule(rules, part, props, path, "if")
        return rules

    def rule(self, rules: list, part: dict, props: dict, path: str, label: str):
        expr = self.compile(part, props)
        if expr is None:
            self.stats.rules_skipped.append((f"{path} ({label})", canon(part)))
        elif expr != "true":
            self.stats.rules_compiled += 1
            rules.append(expr)

    def present(self, p: str, props: dict) -> str | None:
        """Pkl expression that is true when property `p` is set (None if it cannot be expressed)."""
        if p in props:
            return f"{ident(p)} != null"
        if self.rule_open:
            return f"(extra?.containsKey({pkl_literal(p)}) ?? false)"
        return None

    def compile(self, s, props: dict) -> str | None:
        """Compile a schema that only constrains which properties are present (and their values)."""
        if s is True or s == {}:
            return "true"
        if s is False:
            return "false"
        parts = []
        if "if" in s:
            cond = self.compile(s["if"], props)
            then = self.compile(s.get("then", {}), props)
            other = self.compile(s.get("else", {}), props)
            if None in (cond, then, other):
                return None
            parts.append(f"(if ({cond}) {then} else {other})")
        for k, v in s.items():
            if k in DOC_KEYS or k in ("if", "then", "else"):
                continue
            if k == "type" and v == "object":
                continue
            if k == "required":
                checks = [self.present(p, props) for p in v if self.default_of(props, p) is None]
                if None in checks:
                    return None
                parts.append(" && ".join(checks) or "true")
            elif k == "not":
                c = self.compile(v, props)
                if c is None:
                    return None
                parts.append(f"!({c})")
            elif k in ("anyOf", "oneOf", "allOf"):
                cs = [self.compile(b, props) for b in v]
                if None in cs:
                    return None
                if k == "anyOf":
                    parts.append("(" + " || ".join(cs) + ")")
                elif k == "allOf":
                    parts.append("(" + " && ".join(cs) + ")")
                else:
                    parts.append(f"List({', '.join(cs)}).count((it) -> it) == 1")
            elif k == "properties":
                for p, ps in v.items():
                    if p not in props:
                        return None
                    if ps == props[p]:
                        continue  # same schema as the property's declared type, which Pkl already checks
                    d = self.default_of(props, p)
                    c = self.value_cond(ident(p) if d is None else f"({ident(p)} ?? {d})", ps)
                    if c is None:
                        return None
                    if c != "true":
                        parts.append(c if d is not None else f"({ident(p)} == null || {c})")
            elif k == "dependencies":
                for p, dep in v.items():
                    if p not in props:
                        return None
                    if isinstance(dep, list):
                        if any(d not in props for d in dep):
                            return None
                        c = " && ".join(f"{ident(d)} != null" for d in dep) or "true"
                    else:
                        c = self.compile(dep, props)
                        if c is None:
                            return None
                    parts.append(f"({c})" if self.default_of(props, p) is not None else f"({ident(p)} == null || ({c}))")
            elif k in ("minProperties", "maxProperties"):
                count = "List(" + ", ".join(f"{ident(p)} != null" for p in props) + ").count((it) -> it)"
                parts.append(f"{count} {'>=' if k == 'minProperties' else '<='} {v}")
            elif k == "additionalProperties":
                continue  # closed Pkl classes already reject unknown keys
            else:
                return None
        if not parts:
            return "true"
        return parts[0] if len(parts) == 1 else "(" + " && ".join(parts) + ")"

    @staticmethod
    def default_of(props: dict, p: str) -> str | None:
        """Pkl literal of the schema default of property `p` (APISIX fills it in before validating)."""
        ps = props.get(p)
        if isinstance(ps, dict) and "default" in ps:
            return pkl_literal(ps["default"])
        return None

    def value_cond(self, x: str, ps) -> str | None:
        """Condition on a present value `x` (callers add the null guard)."""
        if ps is True or ps == {}:
            return "true"
        if not isinstance(ps, dict):
            return None
        conds = []
        for k, v in ps.items():
            if k in DOC_KEYS:
                continue
            if k == "enum":
                lits = [pkl_literal(e) for e in v]
                if None in lits:
                    return None
                conds.append(f"List({', '.join(lits)}).contains({x})")
            elif k == "const":
                lit = pkl_literal(v)
                if lit is None:
                    return None
                conds.append(f"{x} == {lit}")
            elif k == "type":
                t = {"string": "String", "integer": "Int", "number": "Number", "boolean": "Boolean",
                     "array": "Listing"}.get(v)
                if t is None:
                    return None
                conds.append(f"{x} is {t}")
            elif k == "not":
                c = self.value_cond(x, v)
                if c is None:
                    return None
                conds.append(f"!({c})")
            elif k in ("anyOf", "oneOf"):
                cs = [self.value_cond(x, b) for b in v]
                if None in cs:
                    return None
                conds.append("(" + " || ".join(cs) + ")" if k == "anyOf"
                             else f"List({', '.join(cs)}).count((it) -> it) == 1")
            elif k in ("minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum"):
                if isinstance(v, bool):
                    continue  # draft-4 modifier of minimum/maximum
                op = {"minimum": ">=", "maximum": "<=", "exclusiveMinimum": ">", "exclusiveMaximum": "<"}[k]
                if k == "minimum" and ps.get("exclusiveMinimum") is True:
                    op = ">"
                if k == "maximum" and ps.get("exclusiveMaximum") is True:
                    op = "<"
                conds.append(f"({x} is Number && {x} {op} {pkl_literal(v)})")
            elif k in ("minLength", "maxLength"):
                conds.append(f"({x} is String && {x}.length {'>=' if k == 'minLength' else '<='} {v})")
            elif k == "pattern":
                self.stats.patterns.append(v)
                conds.append(f"({x} is String && {x}.contains({pkl_regex(v)}))")
            elif k in ("minItems", "maxItems"):
                conds.append(f"({x} is Listing && {x}.length {'>=' if k == 'minItems' else '<='} {v})")
            elif k == "uniqueItems":
                if v:
                    conds.append(f"({x} is Listing && {x}.isDistinct)")
            elif k in ("items", "contains"):
                if not isinstance(v, dict):
                    return None
                var = "e" + str(x.count("(") + len(x))  # unique lambda parameter per nesting level
                c = self.value_cond(var, v)
                if c is None:
                    return None
                fn = "every" if k == "items" else "any"
                conds.append(f"({x} is Listing && {x}.toList().{fn}(({var}) -> {c}))")
            else:
                return None
        if not conds:
            return "true"
        return conds[0] if len(conds) == 1 else "(" + " && ".join(conds) + ")"

    # ---------------------------------------------------------- shared types

    def find_shared(self, units: list[tuple[str, dict]]):
        """Object schemas used by more than one plugin module go to Common.pkl."""
        seen = defaultdict(set)

        def walk(node, unit):
            if isinstance(node, dict):
                if node.get("type") == "object" and node.get("properties"):
                    seen[canon(node)].add(unit)
                elif node.get("type") != "object" and "properties" not in node:
                    self.scalar_counts[canon(node)] += 1
                for v in node.values():
                    walk(v, unit)
            elif isinstance(node, list):
                for v in node:
                    walk(v, unit)

        for unit, node in units:
            walk(node, unit)
        main_keys = {canon(self.schema["main"][k]) for k in MAIN}
        self.shared_candidates = {k for k, u in seen.items() if len(u) > 1 and k not in main_keys}

    # ---------------------------------------------------------- run

    def run(self):
        main = self.schema["main"]
        plugins = self.schema["plugins"]
        stream = self.schema.get("stream_plugins", {})
        version = self.schema_name.removeprefix("apisix-").removesuffix(".json")

        apisix = self.module("Apisix.pkl", "apisix.Apisix", [
            f"Core APISIX {version} resources: routes, services, upstreams, consumers, credentials,",
            "consumer groups, SSLs, global rules, plugin configs, protos, stream routes and secrets.",
        ])
        self.module("Common.pkl", "apisix.Common", ["Object types shared by several plugins."])
        self.module("Base.pkl", "apisix.Base", []).handwritten = True
        pmod = self.module("Plugins.pkl", "apisix.Plugins", [
            "Plugin maps of routes, services, consumers and stream routes, and plugin metadata.",
            "",
            "All classes are open: extend them to add types for your own (custom) plugins.",
        ])

        units = [(f"plugin:{n}", p) for n, p in plugins.items()] + [(f"stream:{n}", p) for n, p in stream.items()]
        units += [(f"main:{k}", main[k]) for k in MAIN]
        self.find_shared(units)

        # Core resources. Upstream first, so routes and services reuse it.
        for key, cls in MAIN.items():
            s = main[key]
            canon_key = canon(s)
            name = apisix.unique(cls)
            t = self.emit_class(s, self.merged_properties(s), name, apisix, key)
            self.shared[canon_key] = (apisix, name, t, {"k": "class", "ref": f"Apisix.pkl#{name}"})
        apisix.blocks.insert(0, f"/// The APISIX version these types are generated from.\nconst apisixVersion: String = {pkl_string(version)}")
        self.emit_plugin_entry(apisix, main["plugins"])
        self.emit_secrets(apisix)

        # Plugins.
        fields = {"Plugins": [], "ConsumerPlugins": [], "StreamPlugins": [], "PluginMetadata": []}
        for name in sorted(plugins):
            self.emit_plugin(name, plugins[name], "plugins", "", fields)
        for name in sorted(stream):
            self.emit_plugin(name, stream[name], "stream", "Stream", fields, stream_only=True)
        for cls, entries in fields.items():
            body = []
            for doc, field, t in entries:
                body += [f"  /// {l}" if l else "  ///" for l in doc]
                body.append(f"  {ident(field)}: {nullable(t)}")
            pmod.blocks.append(self.plugin_class_doc(cls) + f"\nopen class {cls} {{\n" + "\n".join(body) + "\n}")
            self.typeinfo[f"Plugins.pkl#{cls}"] = {f: i for (_, f, _), i in zip(entries, self._finfo[cls])}


    @staticmethod
    def plugin_class_doc(cls: str) -> str:
        return {
            "Plugins": "/// Plugins of a route, service, plugin config, global rule or consumer group.",
            "ConsumerPlugins": "/// Plugins of a consumer or credential (auth plugins use their consumer schema).",
            "StreamPlugins": "/// Plugins of a stream route.",
            "PluginMetadata": "/// Plugin metadata (`plugin_metadata` in apisix.yaml), keyed by plugin name.",
        }[cls]

    def emit_plugin(self, name: str, entry: dict, folder: str, prefix: str, fields: dict, stream_only=False):
        mod_name = re.sub(r"[^A-Za-z0-9_]", "_", name)
        doc = [f"APISIX {'stream ' if stream_only else ''}plugin `{name}`."]
        meta = []
        if "type" in entry:
            meta.append(f"type: {entry['type']}")
        if "priority" in entry:
            meta.append(f"priority: {entry['priority']}")
        if "version" in entry:
            meta.append(f"version: {entry['version']}")
        if meta:
            doc.append(", ".join(meta).capitalize())
        if entry.get("encrypt_fields") or entry.get("schema", {}).get("encrypt_fields"):
            ef = entry.get("encrypt_fields") or entry["schema"]["encrypt_fields"]
            doc.append(f"Encrypted by APISIX when stored: {', '.join(ef)}")
        mod = self.module(f"{folder}/{name}.pkl", f"apisix.{folder}.{mod_name}", doc)
        base = prefix + pascal(name)
        pmod = self.modules["Plugins.pkl"]
        summary = doc[1:] if len(doc) > 1 else []

        def field(cls, schema, hint, path):
            t, info = self.type_of(schema, hint, mod, path)
            if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", t):
                # Not a plain local class: name it in the plugin module so Plugins.pkl can refer to it.
                alias = mod.unique(hint + "Config")
                mod.blocks.append(f"typealias {alias} = {t}")
                t = alias
            fields[cls].append((summary, name, pmod.ref(mod, t)))
            self._finfo[cls].append(info)

        s = entry.get("schema") or {"type": "object", "properties": {}}
        if stream_only:
            field("StreamPlugins", s, base, f"stream.{name}")
            return
        field("Plugins", s, base, f"plugin.{name}")
        field("ConsumerPlugins", entry.get("consumer_schema") or s, base + ("Consumer" if entry.get("consumer_schema") else ""),
              f"plugin.{name}.consumer")
        if entry.get("metadata_schema"):
            field("PluginMetadata", entry["metadata_schema"], base + "Metadata", f"plugin.{name}.metadata")

    def emit_plugin_entry(self, apisix: Module, schema: dict):
        item = schema["items"]
        props = item["properties"]
        props = {k: v for k, v in props.items() if k != "additionalProperties"}
        s = {"type": "object", "properties": props, "required": item.get("required", []),
             "additionalProperties": False,
             "description": "An entry of the top-level `plugins` list: hot-reloads the enabled plugins."}
        self.emit_class(s, props, apisix.unique("PluginEntry"), apisix, "plugins[]")

    def emit_secrets(self, apisix: Module):
        for name, s in sorted(self.schema.get("secrets", {}).items()):
            s = json.loads(json.dumps(s))
            s.setdefault("properties", {})
            s["properties"] = {
                "id": {"type": "string", "pattern": f"^{name}/[a-zA-Z0-9-_.]+$",
                       "description": f"`{name}/<id>`; reference values with `$secret://{name}/<id>/<key>`."},
                **s["properties"],
            }
            s["required"] = ["id", *s.get("required", [])]
            s["description"] = f"Secret manager `{name}` (an entry of `secrets` in apisix.yaml)."
            self.emit_class(s, self.merged_properties(s), apisix.unique(pascal(name) + "Secret"), apisix, f"secret.{name}")

    # ---------------------------------------------------------- output

    def write(self):
        for rel, mod in self.modules.items():
            if getattr(mod, "handwritten", False):
                continue
            path = os.path.join(SRC, rel)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(mod.render(self.schema_name))
        os.makedirs(os.path.join(ROOT, "build"), exist_ok=True)
        with open(os.path.join(ROOT, "build", "typeinfo.json"), "w") as f:
            json.dump(self.typeinfo, f, indent=1, sort_keys=True)
        with open(os.path.join(ROOT, "build", "patterns.json"), "w") as f:
            json.dump(sorted(set(self.stats.patterns)), f, indent=1)
        self.write_coverage()

    def write_coverage(self):
        st = self.stats
        main = self.schema["main"]
        lines = [
            f"# Schema coverage ({self.schema_name})",
            "",
            "Generated by `tools/generate.py`. Do not edit.",
            "",
            "| | |",
            "|---|---|",
            f"| HTTP plugins | {len(self.schema['plugins'])} |",
            f"| Stream plugins | {len(self.schema.get('stream_plugins', {}))} |",
            f"| Core resources | {', '.join(MAIN)} , plugins, secrets ({', '.join(sorted(self.schema.get('secrets', {})))}) |",
            f"| Classes generated | {st.classes} |",
            f"| Properties generated | {st.properties} |",
            f"| Cross-field rules compiled to Pkl constraints | {st.rules_compiled} |",
            f"| Cross-field rules **not** checked by Pkl | {len(st.rules_skipped)} |",
            f"| Regex patterns checked by Pkl | {len(set(st.patterns))} |",
            "",
            "Every property of every schema is generated. Value types, enums, ranges, lengths,",
            "patterns, list sizes and uniqueness are checked by Pkl. The items below are not;",
            "APISIX still checks them when it loads the configuration.",
            "",
            "## Not generated",
            "",
        ]
        lines += [f"- `main.{k}`: {why}" for k, why in MAIN_SKIPPED.items() if k in main]
        lines += ["", "## Cross-field rules not checked by Pkl", ""]
        if st.rules_skipped:
            lines += [f"- `{p}`: `{j[:300]}{'…' if len(j) > 300 else ''}`" for p, j in st.rules_skipped]
        else:
            lines.append("None.")
        lines += ["", "## Objects that allow extra keys", "",
                  "APISIX accepts keys the schema does not name in these objects. Their classes extend",
                  "`Base.OpenObject`: named keys are typed properties, other keys go in `extra { ... }`.",
                  "A misspelled property is still a build error.", ""]
        lines += [f"- `{p}`" for p in st.open_objects] or ["None."]
        lines += ["", "## patternProperties generated as named properties", "",
                  "These patterns only name keys (for example `aws`, `header`), so each becomes a typed",
                  "property. Keys that merely contain the name (`my-aws-key`) are not accepted.", ""]
        lines += [f"- `{p}`" for p in st.named_patterns] or ["None."]
        lines += ["", "## Tuple arrays (typed as `Listing<Any>`)", ""]
        lines += [f"- `{p}`" for p in st.tuples] or ["None."]
        lines += ["", "## Other keywords not checked by Pkl", ""]
        lines += [f"- `{p}`: `{k}`" for p, k in st.misc] or ["None."]
        with open(os.path.join(ROOT, "COVERAGE.md"), "w") as f:
            f.write("\n".join(lines) + "\n")


def main():
    if len(sys.argv) != 2:
        sys.exit(f"Usage: {sys.argv[0]} schema/apisix-<version>.json")
    path = sys.argv[1]
    schema = json.load(open(path, encoding="utf-8"))
    for d in ("plugins", "stream"):
        full = os.path.join(SRC, d)
        if os.path.isdir(full):
            for f in os.listdir(full):
                os.remove(os.path.join(full, f))
    gen = Generator(schema, os.path.basename(path))
    gen.run()
    gen.write()
    st = gen.stats
    print(f"generated {len(gen.modules)} modules, {st.classes} classes, {st.properties} properties; "
          f"rules compiled {st.rules_compiled}, not checked {len(st.rules_skipped)}")


if __name__ == "__main__":
    main()
